Chatter/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path,include
import account.urls
import chat.urls
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static
from Chatter import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(account.urls)),
    path('', include(chat.urls)),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('public_chat/',views.chat_view,name="public_chat"),
    path('chat/room/<str:chat_room_name>',views.chat_view,name="chatroom"),
    path('pr_chat/<str:username>',views.do_private_chatroom,name="pr_chat"),
    path('chat/fileupload/<chat_room_name>',views.chat_file_upload, name="chat_file_upload"),
]

chat/models.py
import os

from django.contrib.auth.models import User
from django.db import models
import shortuuid
from PIL import Image

# Create your models here.


class ChatGroup(models.Model):
    group_name = models.CharField(max_length=150,unique=True, default=shortuuid.uuid)
    users_online = models.ManyToManyField(User, related_name='online_in_groups', blank=True)
    members = models.ManyToManyField(User, related_name='chat_groups', blank=True)
    is_private = models.BooleanField(default=False)


    def __str__(self):
        return self.group_name

class GroupMessage(models.Model):
    group = models.ForeignKey(ChatGroup,related_name='chat_messages',on_delete=models.CASCADE)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    body = models.CharField(max_length=300,null=True,blank=True)
    file = models.FileField(upload_to='files/',null=True,blank=True)
    created = models.DateTimeField(auto_now_add=True)

    @property
    def filename(self):
        if self.file:
            return os.path.basename(self.file.name)
        else:
            return None

    def __str__(self):
        if self.body:
            return f'{self.author.username} : {self.body}'
        elif self.file:
            return f'{self.author.username} : {self.filename}'

    class Meta:
        ordering = ['-created']

    @property
    def is_image(self):
        try:
            image = Image.open(self.file)
            image.verify()
            return True
        except:
            return False

chat/forms.py
from django.forms import ModelForm
from django import forms
from .models import *


class ChatmessageCreateForm(ModelForm):
    class Meta:
        model = GroupMessage
        fields = ['body']
        widgets = {
            'body': forms.TextInput(
                attrs={'placeholder': 'Type message...', 'class': 'form-control', 'maxlength': '300',
                       'autofocus': True})
        }

chat/views.py
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.http import Http404, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import ChatmessageCreateForm
from Chatter.utils import login_required

@login_required
def chat_view(request, chat_room_name='public-chat'):
    chat_group = get_object_or_404(ChatGroup, group_name=chat_room_name)
    chat_messages = chat_group.chat_messages.all()[:25]
    form = ChatmessageCreateForm()

    other_user = None
    if chat_group.is_private:
        if request.user not in chat_group.members.all():
            raise Http404()
        for member in chat_group.members.all():
            if member != request.user:
                other_user = member
                break
    if request.method == "POST":
        form = ChatmessageCreateForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.author = request.user
            message.group = chat_group
            message.save()
            context = {
                'message': message,
                'user': request.user
            }
            return render(request, 'partial/chat_message_partial.html', context)

    context = {
        'chat_messages': chat_messages,
        'form': form,
        'other_user': other_user,
        'chat_room_name': chat_room_name

    }

    return render(request, "chat/chat.html", context)


def do_private_chatroom(request, username):
    if request.user.username == username:
        return redirect('home')

    other_user = User.objects.get(username=username)
    # print("the other user",other_user)
    self_chatrooms = request.user.chat_groups.filter(is_private=True)
    # print(self_chatrooms)

    if self_chatrooms.exists():
        for chatroom in self_chatrooms:
            if other_user in chatroom.members.all():
                return redirect('chatroom', chatroom.group_name)

    chatroom = ChatGroup.objects.create(is_private=True)
    chatroom.members.add(other_user, request.user)
    # print(chatroom.group_name)

    return redirect('chatroom', chatroom.group_name)


def chat_file_upload(request, chat_room_name):
    chat_group = get_object_or_404(ChatGroup, group_name=chat_room_name)

    if request.method == "POST":
        file = request.FILES['file']
        message = GroupMessage.objects.create(
            file=file,
            author=request.user,
            group=chat_group,
        )

        channel_layer = get_channel_layer()
        event = {
            'type': 'message_handler',
            'message_id': message.id,
        }

        async_to_sync(channel_layer.group_send)(
            chat_room_name, event
        )

        return HttpResponse()

chat/templates/chat/chat.html
{% extends 'base.html' %}

{% block content %}
<main class="content">
    <div class="container p-0" style="width:650px;margin-top:30px;">
        <div class="card">
            <div class="row g-0">
                <div class="col-12 col-lg-7 col-xl-12">
                    <div class="py-2 px-4 border-bottom d-none d-lg-block">
                        {% if other_user %}
                                <img class="account-image rounded-circle m-auto d-block "   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="{{other_user.profile.profile_image.url}}"  width="55" height="65" style="padding-top:10px;border-radius:10px;">
                                <p class="card-text" style="padding-left:60px;"><span style="font-size:18px;color:brown;font-weight:bold;margin-left:219px;">{{other_user.username}}</span></p>
                        {% else %}
                        <h5 style="color:green;">Welcome to the community,</h5>
                        <p style="color:blue;">Here, all the messages you have sent visible to all the members in the chat.</p>
                      {% include 'chat/online_count.html' %}online
                        {% endif %}
                    </div>

                    <div class="position-relative " >
                        <div class="chat-messages p-4" id="chat_messages">
                            {% for message in chat_messages reversed %}
                            {% include 'chat/chat_message_part.html'%}
                            {% endfor %}
                        </div>
                    </div>

                    <div class="flex-grow-0 py-3 px-4 border-top">
                        <div class="input-group d-lg-block">
                            <form id="chat_message_form"
                                  hx-ext="ws"
                                  ws-connect="/ws/chatroom/{{ chat_room_name }}"
                                  ws-send
                                  _="on htmx:wsAfterSend reset() me">
                                {% csrf_token %}
                                {{ form }}
                            </form><br>
                            <form id="chat_file_form" enctype="multipart/form-data"
                                hx-post="{% url 'chat_file_upload' chat_room_name %}"
                                hx-target="#chat_messages"
                                hx-swap="beforeend"
                                _="on htmx:beforeSend reset() me" >
                                {% csrf_token %}
                                <input type="file" name="file" id="id_file" >
                                <button type="submit" class="btn btn-info">Submit File</button>
                             </form>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</main>


<style>

.chat-online {
    color: #34ce57
}

.chat-offline {
    color: #e4606d
}

.chat-messages {
    display: flex;
    flex-direction: column;
   height: 500px;
    overflow-y: scroll
}

.chat-message-left,
.chat-message-right {
    display: flex;
    flex-shrink: 0
}

.chat-message-left {
    margin-right: auto
}

.chat-message-right {
    flex-direction: row-reverse;
    margin-left: auto
}
.py-3 {
    padding-top: 1rem!important;
    padding-bottom: 1rem!important;
}
.px-4 {
    padding-right: 1.5rem!important;
    padding-left: 1.5rem!important;
}
.flex-grow-0 {
    flex-grow: 0!important;
}
.border-top {
    border-top: 1px solid #dee2e6!important;
}
</style>
{% endblock %}

{% block javascript %}
<script>

    function scrollToBottom(time=0) {
        setTimeout(function() {
            const container = document.getElementById('chat_messages');
            container.scrollTop = container.scrollHeight;
        }, time);
    }
    scrollToBottom()

</script>
{% endblock %}

chat/templates/chat/chat_message_part.html
{% if message.author == user %}
 <div class="chat-message-right pb-4">
     <div>
         <img src="{{ message.author.profile.profile_image.url }}"
              class="rounded-circle mr-1" alt="" width="40" height="40">
     </div>
     <div class="flex-shrink-1 bg-light rounded py-2 px-3 mr-3">
    <div class="font-weight-bold mb-1">You</div>
         {% include 'partial/text_file_message_part.html' %}
<!--    {{ message.body }}-->
</div>
 </div>

 {% else %}

 <div class="chat-message-left pb-4">
     <div>
         <a href="{% url 'view_account' user_id=message.author.id %}">
         <img src="{{ message.author.profile.profile_image.url }}"
              class="rounded-circle mr-1" alt="" width="40" height="40">
         </a>
     </div>
     <div class="flex-shrink-1 bg-light rounded py-2 px-3 mr-3">
    <div class="font-weight-bold mb-1">{{message.author.username}}</div>
         {% include 'partial/text_file_message_part.html' %}
     </div>
 </div>
 {% endif %}

chat/templates/chat/online_count.html
<span id="online-count" style="color:brown;">
    {{ online_count }}
</span>